version: '3'

services:

  social-network-api:
    container_name: social-network
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: postgres-social
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=social
      - POSTGRES_PASSWORD=social